// Generated by gencpp from file robot_functionality/Add_Two_ints.msg
// DO NOT EDIT!


#ifndef ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTS_H
#define ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTS_H

#include <ros/service_traits.h>


#include <robot_functionality/Add_Two_intsRequest.h>
#include <robot_functionality/Add_Two_intsResponse.h>


namespace robot_functionality
{

struct Add_Two_ints
{

typedef Add_Two_intsRequest Request;
typedef Add_Two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Add_Two_ints
} // namespace robot_functionality


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_functionality::Add_Two_ints > {
  static const char* value()
  {
    return "9e6a9d11554d919181816798243e5e82";
  }

  static const char* value(const ::robot_functionality::Add_Two_ints&) { return value(); }
};

template<>
struct DataType< ::robot_functionality::Add_Two_ints > {
  static const char* value()
  {
    return "robot_functionality/Add_Two_ints";
  }

  static const char* value(const ::robot_functionality::Add_Two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::robot_functionality::Add_Two_intsRequest> should match
// service_traits::MD5Sum< ::robot_functionality::Add_Two_ints >
template<>
struct MD5Sum< ::robot_functionality::Add_Two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_functionality::Add_Two_ints >::value();
  }
  static const char* value(const ::robot_functionality::Add_Two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_functionality::Add_Two_intsRequest> should match
// service_traits::DataType< ::robot_functionality::Add_Two_ints >
template<>
struct DataType< ::robot_functionality::Add_Two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_functionality::Add_Two_ints >::value();
  }
  static const char* value(const ::robot_functionality::Add_Two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_functionality::Add_Two_intsResponse> should match
// service_traits::MD5Sum< ::robot_functionality::Add_Two_ints >
template<>
struct MD5Sum< ::robot_functionality::Add_Two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_functionality::Add_Two_ints >::value();
  }
  static const char* value(const ::robot_functionality::Add_Two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_functionality::Add_Two_intsResponse> should match
// service_traits::DataType< ::robot_functionality::Add_Two_ints >
template<>
struct DataType< ::robot_functionality::Add_Two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_functionality::Add_Two_ints >::value();
  }
  static const char* value(const ::robot_functionality::Add_Two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTS_H
