// Generated by gencpp from file robot_functionality/Add_Two_intsRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSREQUEST_H
#define ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_functionality
{
template <class ContainerAllocator>
struct Add_Two_intsRequest_
{
  typedef Add_Two_intsRequest_<ContainerAllocator> Type;

  Add_Two_intsRequest_()
    : a(0)
    , b(0)  {
    }
  Add_Two_intsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Add_Two_intsRequest_

typedef ::robot_functionality::Add_Two_intsRequest_<std::allocator<void> > Add_Two_intsRequest;

typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsRequest > Add_Two_intsRequestPtr;
typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsRequest const> Add_Two_intsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator1> & lhs, const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator1> & lhs, const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_functionality

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_functionality/Add_Two_intsRequest";
  }

  static const char* value(const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request\n"
"int32 a \n"
"int32 b\n"
"\n"
;
  }

  static const char* value(const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Add_Two_intsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_functionality::Add_Two_intsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSREQUEST_H
