// Generated by gencpp from file robot_functionality/Add_Two_intsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSRESPONSE_H
#define ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_functionality
{
template <class ContainerAllocator>
struct Add_Two_intsResponse_
{
  typedef Add_Two_intsResponse_<ContainerAllocator> Type;

  Add_Two_intsResponse_()
    : z(0)  {
    }
  Add_Two_intsResponse_(const ContainerAllocator& _alloc)
    : z(0)  {
  (void)_alloc;
    }



   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Add_Two_intsResponse_

typedef ::robot_functionality::Add_Two_intsResponse_<std::allocator<void> > Add_Two_intsResponse;

typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsResponse > Add_Two_intsResponsePtr;
typedef boost::shared_ptr< ::robot_functionality::Add_Two_intsResponse const> Add_Two_intsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator1> & lhs, const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator1> & lhs, const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_functionality

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "504cd75e20b3c55076aefbd8b1dcfe72";
  }

  static const char* value(const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x504cd75e20b3c550ULL;
  static const uint64_t static_value2 = 0x76aefbd8b1dcfe72ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_functionality/Add_Two_intsResponse";
  }

  static const char* value(const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response\n"
"int64 z\n"
;
  }

  static const char* value(const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Add_Two_intsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_functionality::Add_Two_intsResponse_<ContainerAllocator>& v)
  {
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_FUNCTIONALITY_MESSAGE_ADD_TWO_INTSRESPONSE_H
