// Generated by gencpp from file robot_functionality/Gettting_TransformResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMRESPONSE_H
#define ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>

namespace robot_functionality
{
template <class ContainerAllocator>
struct Gettting_TransformResponse_
{
  typedef Gettting_TransformResponse_<ContainerAllocator> Type;

  Gettting_TransformResponse_()
    : Transform()
    , Success(false)  {
    }
  Gettting_TransformResponse_(const ContainerAllocator& _alloc)
    : Transform(_alloc)
    , Success(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _Transform_type;
  _Transform_type Transform;

   typedef uint8_t _Success_type;
  _Success_type Success;





  typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Gettting_TransformResponse_

typedef ::robot_functionality::Gettting_TransformResponse_<std::allocator<void> > Gettting_TransformResponse;

typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformResponse > Gettting_TransformResponsePtr;
typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformResponse const> Gettting_TransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator1> & lhs, const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Transform == rhs.Transform &&
    lhs.Success == rhs.Success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator1> & lhs, const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_functionality

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f385f95c3287739c267f3e35e012760";
  }

  static const char* value(const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f385f95c3287739ULL;
  static const uint64_t static_value2 = 0xc267f3e35e012760ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_functionality/Gettting_TransformResponse";
  }

  static const char* value(const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response\n"
"geometry_msgs/TransformStamped Transform\n"
"bool Success\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Transform);
      stream.next(m.Success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gettting_TransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_functionality::Gettting_TransformResponse_<ContainerAllocator>& v)
  {
    s << indent << "Transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.Transform);
    s << indent << "Success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMRESPONSE_H
