// Generated by gencpp from file robot_functionality/Gettting_TransformRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMREQUEST_H
#define ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_functionality
{
template <class ContainerAllocator>
struct Gettting_TransformRequest_
{
  typedef Gettting_TransformRequest_<ContainerAllocator> Type;

  Gettting_TransformRequest_()
    : Frame_id()
    , Child_Frame_id()  {
    }
  Gettting_TransformRequest_(const ContainerAllocator& _alloc)
    : Frame_id(_alloc)
    , Child_Frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Frame_id_type;
  _Frame_id_type Frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Child_Frame_id_type;
  _Child_Frame_id_type Child_Frame_id;





  typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Gettting_TransformRequest_

typedef ::robot_functionality::Gettting_TransformRequest_<std::allocator<void> > Gettting_TransformRequest;

typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformRequest > Gettting_TransformRequestPtr;
typedef boost::shared_ptr< ::robot_functionality::Gettting_TransformRequest const> Gettting_TransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator1> & lhs, const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Frame_id == rhs.Frame_id &&
    lhs.Child_Frame_id == rhs.Child_Frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator1> & lhs, const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_functionality

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb2973aa1cf0610d54f3677ba9015c26";
  }

  static const char* value(const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb2973aa1cf0610dULL;
  static const uint64_t static_value2 = 0x54f3677ba9015c26ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_functionality/Gettting_TransformRequest";
  }

  static const char* value(const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request \n"
"string Frame_id\n"
"string Child_Frame_id\n"
;
  }

  static const char* value(const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Frame_id);
      stream.next(m.Child_Frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gettting_TransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_functionality::Gettting_TransformRequest_<ContainerAllocator>& v)
  {
    s << indent << "Frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Frame_id);
    s << indent << "Child_Frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Child_Frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_FUNCTIONALITY_MESSAGE_GETTTING_TRANSFORMREQUEST_H
