(cl:defpackage robot_functionality-srv
  (:use )
  (:export
   "ADD_TWO_INTS"
   "<ADD_TWO_INTS-REQUEST>"
   "ADD_TWO_INTS-REQUEST"
   "<ADD_TWO_INTS-RESPONSE>"
   "ADD_TWO_INTS-RESPONSE"
   "GETTTING_TRANSFORM"
   "<GETTTING_TRANSFORM-REQUEST>"
   "GETTTING_TRANSFORM-REQUEST"
   "<GETTTING_TRANSFORM-RESPONSE>"
   "GETTTING_TRANSFORM-RESPONSE"
  ))

