#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import Imu
def imu_callback(msg):
    msg.header.frame_id = "base_footprint"
    imu_ekf.publish(msg)


if __name__ == "__main__":
    rospy.init_node('imu_Republisher')
    imu_ekf = rospy.Publisher("/imu_ekf",Imu,queue_size=10)
    imu_sub= rospy.Subscriber("/imu", Imu, imu_callback)
    rospy.spin()  